version: "3.9"
services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "8001:8001"
    networks:
      - app-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Vettely417vzvvzv&
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge